In [1]:
import pandas as pd
import numpy as np
from sklearn import naive_bayes as nb
import os
import matplotlib

In [2]:
numbers=[]
for i in xrange(1,14):
    numbers.append([])

In [3]:
gestures = pd.DataFrame()
labels = pd.Series()
labels_array=[]
sizes = [1];
i=0
for root, dirs, files in os.walk("MicrosoftGestureDataset-RC/data"):
    for file in files:
        if file.endswith(".csv"):
            temp = pd.read_csv(os.path.join(root,file),sep=' ',header=None)
#             print int(file[file.find('_',3)+1:file.rfind('_')].replace('A',''))
            numbers[int(file[file.find('_',3)+1:file.rfind('_')].replace('A',''))].append(len(temp))
#             print file
#             gestures[i] = temp.values.flatten()
#             labels_array.append(file[file.find('_',3)+1:file.rfind('_')].replace('A',''))
#             sizes.append(len(temp))
            i=i+1;
print str(i)+" gesture files loaded"

# gestures

594 gesture files loaded

In [6]:
df=pd.DataFrame(numbers)
df.T.describe().T

    count         mean          std    min      25%     50%      75%     max
0     0.0          NaN          NaN    NaN      NaN     NaN      NaN     NaN
1    50.0  1448.340000   759.144218  652.0  1020.25  1193.0  1575.00  5237.0
2    50.0  1292.740000   509.403084  539.0   988.50  1124.0  1452.00  3093.0
3    50.0  1091.500000   242.585415  639.0   894.00  1063.0  1283.75  1721.0
4    50.0  1094.500000   278.765006  735.0   910.75  1008.0  1282.75  2083.0
5    48.0  1270.125000  1248.668919  643.0   830.25   987.0  1281.00  9340.0
6    49.0  1122.163265   295.430219  670.0   904.00  1025.0  1394.00  1799.0
7    50.0  1161.480000   208.605989  804.0  1019.50  1112.5  1274.75  1716.0
8    50.0  1095.220000   324.573648  715.0   851.50  1045.5  1209.75  2454.0
9    50.0  1368.740000   331.734022  933.0  1127.75  1272.5  1515.00  2308.0
10   48.0  1209.958333   437.300907  822.0   940.25  1097.0  1360.50  3538.0
11   49.0  1601.979592   757.450369  768.0  1163.00  1524.0  1847.00  5775.0
12   50.0  1077.460000   220.088499  606.0   923.50  1046.0  1182.25  1554.0